FROM gcr.io/ris-registry-shared/rstudio:4.1.2

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update --fix-missing && \
apt-get install -y build-essential \
libcurl4-gnutls-dev libxml2-dev \
libssl-dev \
libssh-dev \
default-jdk && \
apt-get clean
